added syntax validate the Terraform script

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,4 +1,5 @@
-name: Validate terraform fmt
+name: Validate Terraform Files
+
 on:
   pull_request:
     branches:
@@ -10,28 +11,30 @@ permissions:
   contents: read
 
 jobs:
-  validate:
+  validate_formatting:
     runs-on: ubuntu-latest
-    name: terraform fmt check
+    name: Terraform fmt Check
     outputs:
       CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 2
-      - name: Fetch changed files
+
+      - name: Fetch Changed Files
         id: pr_files
         uses: jitterbit/get-changed-files@v1
         with:
           format: "space-delimited"
-      - name: Configure terraform
+
+      - name: Configure Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.2.4
-      - name: Validate terraform fmt (added_modified)
+
+      - name: Validate Terraform Formatting (fmt)
         run: |
           set +e
-
           echo "CHECK_STATUS=0" >> $GITHUB_ENV
 
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
@@ -39,7 +42,7 @@ jobs:
 
             if [[ $changed_file == *.tf ]]; then
               terraform fmt -check $changed_file
-              FMT_STATUS=$(echo $?)
+              FMT_STATUS=$?
 
               if [[ $FMT_STATUS -ne 0 ]]; then
                 echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
@@ -47,6 +50,29 @@ jobs:
               fi
             fi
           done
-      - name: Process check
+
+      - name: Process Formatting Check
         if: always()
         run: exit $CHECK_STATUS
+
+  validate_syntax:
+    runs-on: ubuntu-latest
+    name: Terraform Syntax Check
+    needs: validate_formatting  # Ensures formatting passes first
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Configure Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.2.4
+
+      - name: Initialize Terraform
+        run: |
+          echo "🚀 Running terraform init"
+          terraform init -backend=false
+
+      - name: Run Terraform Validation (validate)
+        run: |
+          echo "🚀 Running terraform validate"
+          terraform validate || (echo "❌ Terraform validation failed!" | tee -a $GITHUB_STEP_SUMMARY && exit 1)
